# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638cb60f1702700f3eb1bdc615c5984fe61e852b1a7b40a71497769924dc817ef09e847e790ef05cff3891cbb8bf3fc5680e61c19ec845d462a7c053e4dfc66f

test:
  secret_key_base: 9d0332a5349b89888ebfb8ab3822a804686db8c94a1d1349d1af74c670ab7cae9cf54f1af047f34a0bf0b6d859f20f6df31690c65cacbfb48af9ec5595eaf906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
